### ISSUE TITLE
log files created by root user

### ISSUE THREAD

**Issue by vincent-peugnet** [club-1/hosting#1]
at this time, `.log` files are created by root user, they cant be deleted by classic low level user like me :'(

**Comment by n-peugnet** [comment]
I know but I didn't find any easy enough solution to this issue.

For now these files are deleted at the same time as the virtualhosts

If I find a better solution I will give you an update

**Comment by n-peugnet** [comment]
Hmm maybe I could just `chown` these in the vhost creation script

**Comment by n-peugnet** [comment]
This is not a good idea to just chown the files because if the user deletes them they will be recreated with root user.

Moreover I think this is a good thing that a user can't delete these files and thus, the directory containing it. Because it means it is related to a virtual host
