### ISSUE TITLE
Looking for a good groupware ? or not the solution ?

### ISSUE THREAD

**Issue by vincent-peugnet** [club-1/hosting#13]
I'm wondering what would be the best software solution to remplace google mail / calendar / contact.

After a few search, I've checked Sogo https://sogo.nu/

It's looked interesting after testing the material UI

**Comment by n-peugnet** [comment]
This requires #9

**Comment by n-peugnet** [comment]
For caldav and carddav (calendar, notes, tasks, contacts), I was wondering if separate the server and the client (as for matrix and riot) would be a good idea.

For exemple [Radicale](https://radicale.org/2.1.html) could be the server and then a web client could be installed like riot.

**Comment by vincent-peugnet** [comment]
> For exemple Radicale could be the server and then a web client could be installed like riot.

Yes, I've checked Radicale, but I could test anything of it, but for me it looked like what we need.

**Comment by vincent-peugnet** [comment]
solved by roundcube + card dav puglin + cald dav calendar plugin
