### ISSUE TITLE
Software add : invoiceplane

### ISSUE THREAD

**Issue by vincent-peugnet** [club-1/hosting#15]
I'd like to test/use a Invoice software to manage my invoices.

After some searching, I've tested :

- [SolidInvoice](https://github.com/SolidInvoice/SolidInvoice) - Too basic
- [invoiceninja](https://github.com/invoiceninja/invoiceninja) - Too big, and need to send mail itself
- [InvoicePlane](https://github.com/InvoicePlane/InvoicePlane) - seems perfectly sized, mail are send using SMTP.

I can't test the Demo as it seems offline, but I've checked the documentation that include a lots of screenshots. I think it's a relatively lightweight software as it only use databases, PDF creation, SMTP email sending.

Specs :
-----------

- Open Source
- Community driven
- Not so active developpement right now but still there
- Codeigniter Framework

Requirements :
-----------------------

- PHP
- MySQL

**Comment by n-peugnet** [comment]
We finally opted for a per user manual install for this software.
