### ISSUE TITLE
Synapse SMTP conf

### ISSUE THREAD

**Issue by n-peugnet** [club-1/hosting#22]
To be able to send mails (en recover lost passwords). Do you have a good email address with SMTP access that we could use @vincent-peugnet ?

**Comment by vincent-peugnet** [comment]
Mmh, no.
But we could create one ?
I could create a [Rise Up](https://riseup.net/email) account
https://riseup.net/fr/email/clients they allow SMT remote control.
What name would you choose ?
`club1@riseup.net` ?

**Comment by n-peugnet** [comment]
the email of the account is not that important as we can change the sender with SMTP. We just need an SMTP access.

**Comment by vincent-peugnet** [comment]
wow okay, but is'nt it a thing that mail client does'nt like (for example gmail comparing SMTP adress with sender, or something like that...?)
I mean is it a way that will throw our mails more often in the trash ?

**Comment by n-peugnet** [comment]
Usually not. At least that's what I was doing for some time without problems. I mean, we can already test it and see if it works and passes the Gmail spam filter.

**Comment by n-peugnet** [comment]
Now that #21 is done we can move on with this and use a synapse@club1.fr (or something else) email address

**Comment by n-peugnet** [comment]
Done
