### ISSUE TITLE
Install Baserow when it will be available in July

### ISSUE THREAD

**Issue by vincent-peugnet** [club-1/hosting#23]
As a reminder : Baserow is the future open source alternative to airtable.

https://baserow.io/

According to their road map, the open source version should be available in July.

**Comment by vincent-peugnet** [comment]
I've checked the demo, it's pretty empty of functionality but the base is perfect. It's identical to airtable witch is the best for me.

**Comment by n-peugnet** [comment]
[Hey](https://baserow.io/blog/open-source-release-of-baserow) !

**Comment by vincent-peugnet** [comment]
Sad news : there will be a premium version of Baserow...

https://baserow.io/premium

**Comment by n-peugnet** [comment]
ah ouais chaud, même pour la version self-hostée:

> Self hosting and pricing
> 
> The premium version can be used in combination with the hosted and self hosted version. Once released everyone will be able to purchase a license to unlock the features in the self hosted version. The price will vary between € 5 and € 20 per user / month.

**Comment by vincent-peugnet** [comment]
Let's give up Baserow and wait for a more suitable open source solution. :coffin:
