### ISSUE TITLE
Unix cloud

### ISSUE THREAD

**Issue by n-peugnet** [club-1/hosting#28]
# Propose a cloud application to our users.

Requirements:
1. feel comparable to popular clouds app, for instance GoogleDrive.
2. properly integrated with the unix user's home.
3. synchronization with other devices

Propositions:

## WebDav server + JS WebDav front

- Back end using PHP
- Front end using https://github.com/perry-mitchell/webdav-client

**Comment by vincent-peugnet** [comment]
https://github.com/club-1/unix-cloud
