### ISSUE TITLE
Adding some new softs to manage music libraries

### ISSUE THREAD

**Issue by vincent-peugnet** [club-1/hosting#3]
List of music management CLI softwares that should be installed on the server

- [x] kid3
- [x] beets

[kid3](https://kid3.sourceforge.io/)
-----------------------------------

 Id3 tag editor

```
sudo add-apt-repository ppa:ufleisch/kid3
sudo apt-get update
sudo apt-get install kid3-cli
```

[beets](https://beets.io/)
-------------------------------

music importer and musicbrainz matching algorithm

> Is it possible to allow each users to have it's own [config file](https://beets.readthedocs.io/en/stable/guides/main.html#configuring) ??

**Comment by n-peugnet** [comment]
I will look into kid3 this evening. But about beets config file it is following the [xdg base directory specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html) son thé configuration ils already stored on a per user basis.

**Comment by vincent-peugnet** [comment]
when is Kid3 coming ??????????? @n-peugnet

**Comment by n-peugnet** [comment]
cé fé

**Comment by vincent-peugnet** [comment]
After loooong time of analyzing different options, I've finally choose to use `beets` as my main music manager.

that is why, it would be better to encode files in `.opus` using the `convert plugin` (that is just using ffmpeg to convert the film during the importation process).

[plugin doc](https://beets.readthedocs.io/en/v1.3.17/plugins/convert.html)
