### ISSUE TITLE
Install nextcloud

### ISSUE THREAD

**Issue by n-peugnet** [club-1/hosting#4]
As [explained here](https://docs.nextcloud.com/server/17/admin_manual/installation/source_installation.html#example-installation-on-ubuntu-18-04-lts-server)

**Comment by vincent-peugnet** [comment]
About accessing the files manualy
----------------------------------------------

It looks like the nextcloud folder structure is not only virtual, but as well on the hard drive. That way, files can be moved, uploaded or downloaded using ssh, ftp... You just need to re-scan manually after any change to update the database.

[https://help.nextcloud.com/t/can-i-move-files-direct-to-nextcloud/33594](https://help.nextcloud.com/t/can-i-move-files-direct-to-nextcloud/33594)

That's a good news I think, if it's correct

**Comment by n-peugnet** [comment]
For now, nextcloud will not be added as I didn't find a way to integrate it correctly with the current _personal space_.
