### ISSUE TITLE
Contact adress that is forwarded to administrative members.

### ISSUE THREAD

**Issue by vincent-peugnet** [club-1/hosting#45]
As explain in the page [rejoindre le club](https://club1.fr/rejoindre/), the only way to get in touch with Club1 is to use *Matrix*. It's obviously a pleasure to be contacted that way, but it may be quicker and easier for most users to just send a email.

We could have a public official contact email like:

```
contact@club1.fr
```

To save Club1 member from checking an additionnal email adress, this would be cool if mails recieved this way could be directly forwarded to a list of concerned members.

This lead us to a interesting question: __Who would be on the list ?__

My suggestion is:

Club1 members that want to be on the list. This way it don't create a separation like admin/users. As it is a comunication role, anybody that feel good to be part of this team could join !

If this would be the choosen setting, we may need to express it somewhere to make it clear.

**Comment by n-peugnet** [comment]
Done
