### ISSUE TITLE
Reconsider possible usages of Syncthing

### ISSUE THREAD

**Issue by vincent-peugnet** [club-1/hosting#53]
Syncthing is not easy to embrace for me.

### Advantages I see:

- bi-directionnal
- encrypted
- infinite quantity of devices
- live sync

### Risk I imagine:

- too much CPU usage (on the server)

## The idea

From what I understand, Syncthing allow any device to be synced with any device, without any main server, in approx' real time, bi-directionally. I can imagine having a folder on my PC storing documents I use a lot. And maybe I want them to be sync in my personal space on the server. And maybe even with my phone.

There seems to be a possibility to have a [webGUI](https://docs.syncthing.net/users/guilisten.html) and [LDAP authentication](https://docs.syncthing.net/users/ldap.html). I'm not sure if it is possible, but if it would allow CLUB1 members to connect to somethings like `sync.club1.fr` to display their device ID and configure sync of one or more folder with others, this seems interesting to me.

As [their FAQ](https://docs.syncthing.net/users/faq.html#is-syncthing-my-ideal-backup-application) said: Let's keep in mind that Syncthing ain't no backup software. And be clear that it's not the use case for members.

I like the fact that the server could be only a part in a deep sync scenario imagined by crazy users.

**Comment by n-peugnet** [comment]
https://docs.syncthing.net/users/faq.html#how-do-i-configure-multiple-users-on-a-single-machine

**Comment by vincent-peugnet** [comment]
Would it still be possible for users to run their own instance of syncthing in their home directory ?
Then, a tutorial explaining how to do it could be interesting ?

**Comment by n-peugnet** [comment]
No, because of the firewall
