### ISSUE TITLE
RSS aggregator web interface for members

### ISSUE THREAD

**Issue by vincent-peugnet** [club-1/hosting#56]
RSS is not easy to discover. We thought with @Mement0o  that maybe, if we found a basic web aggregator supporting LDAP, this would be a nice feature to help members stepping into RSS world.

**Comment by n-peugnet** [comment]
Definitely, it would probably be TTRSS. Of course I'm open to better suggestions

**Comment by vincent-peugnet** [comment]
### [FreshRSS](https://github.com/FreshRSS/FreshRSS)

PHP.
No LDAP yet. people asked for it in this issue: https://github.com/FreshRSS/FreshRSS/issues/1053

### [Miniflux v2](https://github.com/miniflux/v2)

Go.
[list of auth methods](https://miniflux.app/features.html#auth).No issues talk about LDAP.

**Comment by n-peugnet** [comment]
Miniflux sounded cool yes. It supports OpenId. And mot importantly its a daemon, so i hope it fetches newsfeeds itself regularly (what PHP based aggregators like TTRSS and FreshRSS don't do)

**Comment by n-peugnet** [comment]
Also there is a [Debian package for TTRSS](https://packages.debian.org/bookworm/tt-rss).

**Comment by n-peugnet** [comment]
Done: <https://rss.club1.fr>
