### ISSUE TITLE
Installing Matrify

### ISSUE THREAD

**Issue by vincent-peugnet** [club-1/hosting#6]
Users might want to have the possibility to use self hosted easy database tools. Maybe [Matrify](https://www.matrify.com/) could then be a good tool to add..?

Here is the installation process : https://www.matrify.com/en/support-docs-server-install

It's not open source but free as it's self hosted.

**Comment by vincent-peugnet** [comment]
After a good reading of the install instructions, it appears that it's not totally free....

So, just forget about it

**Comment by n-peugnet** [comment]
Okkool
