### ISSUE TITLE
utf-8 by default ?  

### ISSUE THREAD

**Issue by vincent-peugnet** [club-1/hosting#66]
Should the apache server be set by default to utf8 ?

**Comment by n-peugnet** [comment]
### Advantages :

- No need to specify the meta charset in HTML files
- Almost every editors (if not all) now encodes plain text files in UTF-8 by default
- It is still possible to override it using `.htaccess`.

### Downsides:

- This will break files encoded in the old default iso-8859-1
- It is not overridable in the HTML body

### References

- https://www.w3.org/International/questions/qa-html-encoding-declarations
- https://httpd.apache.org/docs/2.4/en/mod/core.html#adddefaultcharset
- https://stackoverflow.com/a/10926894/7837581

### Decision

I think this worth it, as no files are encoded in iso-8859-1 these days. And it is still possible to override it in a `.htaccess` (though not very user friendly).
