### ISSUE TITLE
Switch to another internet provider : OVH telecoms

### ISSUE THREAD

**Issue by vincent-peugnet** [club-1/hosting#67]
Check for another internet provider : free.fr

**Comment by n-peugnet** [comment]
Free would not add a big benefit, as rDNS are only working for IPv4. OVH on the other hand should allow us to setup rDNS for both IPv4 and IPv6, as well as replacing the router be a more performant one (e.g. the EdgeRouter4 I have in stock).

**Comment by n-peugnet** [comment]
Moved to https://forum.club1.fr/d/37
