### ISSUE TITLE
photography managing tool

### ISSUE THREAD

**Issue by vincent-peugnet** [club-1/hosting#68]
considering **Photoprism**:

I've been checking their gihub issues and discussions.

They are [currently working on multi user](https://github.com/photoprism/photoprism/projects/5#card-50044014) and [PostgreSQL is officially on their roadmap](https://docs.photoprism.app/release-notes/#november-28-2021).

https://github.com/photoprism/photoprism

Question about it would be:

- possibility to disallow RAW conversion and video conversion (as the server is not meant for those heavy works)
- how much storage space is allowed for users (HDD vs SSD)

**Comment by vincent-peugnet** [comment]
# Photoview

I've discovered another tool that seems to better suit our style: **Photoview**

> The file system is the Source of Truth, this is the most important value for the software. There are two big advantages to letting the file system dictate the structure and organisation of the media. Firstly, it provides a lot of flexibility for organisation, as it lets you use what ever tool that can modify the file system for organising the media, let it be a simple file server like FTP or NTFS or a cloud service like [Nextcloud](https://photoview.github.io/en/docs/usage-nextcloud/). Secondly, it removes dependency; you can uninstall Photoview at any time and your photos are still organised.

from Photoview Documentation

It's already multi user but there is no LDAP yet. issue: https://github.com/photoview/photoview/issues/272

It's written in Go and TypeScript.

**Comment by n-peugnet** [comment]
Déplacé vers https://forum.club1.fr/d/10-photoview-logiciel-de-gestion-de-photo
