### ISSUE TITLE
Find the next tool for tickets managing

### ISSUE THREAD

**Issue by vincent-peugnet** [club-1/hosting#76]
In addition to to all github privacy problems, using it for incidents, tickets, Q&A and projects ideas is not even practical.

Most of the issues of this repo could be converted to another solution.

What tool would we use for this ?

A idea could be to use a **forum**, that would as well add a slow lane discussion feed, that will combine well with our usage of Matrix.
In this forum, we could add categories like Ideas, Problemes, Projects... to manage those discussions.

More technically, we could use Flarum, with LDAP, categories and Best Answer Extension.

**Comment by n-peugnet** [comment]
This has been started and is currently under testing here: https://forum.club1.fr/

**Comment by n-peugnet** [comment]
This is done
