### ISSUE TITLE
Configure an LDAP server for centralized authentication

### ISSUE THREAD

**Issue by n-peugnet** [club-1/hosting#9]
LDAP is the way to go.

- [x] install and configure openLDAP
- [x] configure PAM to use LDAP
- [x] migrate existing users to LDAP
- [x] update personalspace scripts to use LDAP.
  `ldapscripts` package can help with some of the replacements.
  - [x] replace useradd usages with ldapadduser `grep -nr useradd src lib`
  - [x] replace usermod usages by ldapusermodify (create according diff for each option) `grep -nr usermod src lib`
    `usermod -s` can be replaced with `chsh.ldap` from `nslcd-utils`
  - [x] replace userdel usages with ldapdeleteuser `grep -nr userdel src lib`
- [x]  delete unix users that exist on ldap, otherwise this can create strange situations
  - [x]  ~~this asks the question of which user must stay as a unix user~~ (my account sould probably stay a unix user, ~~or maybe another admin account should be created~~)
  - [x] delete current test LDAP database
  - [x] run the [migration tools](https://wiki.debian.org/LDAP/MigrationTools) once again to export the users and group
    - [x] remove system groups from this migration
    - [x] remove some useless groups before running the migration
- [x] make sure LDAP database is included in the backup and can be restored
- [ ] #49
- [x] ~~make MySql use LDAP~~ (this might not be useful as the current PAM based solution would already work with ldap through nslcd)

**Comment by n-peugnet** [comment]
I've updated some of the tasks that are blocking ldap adoption @vincent-peugnet

**Comment by vincent-peugnet** [comment]
Why not not storing groups on LDAP but let them live their life seemlessly in unix?

**Comment by n-peugnet** [comment]
closing this issue as LDAP is in a safe and usable state for now
